---
name: cd-cd pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: Linux
    steps:
      - name: checkout code
        uses: actions/checkout@v4.2.2
      - name: set up node environment
        uses: actions/setup-node@v3
        with: 
         node-version: "14"
      - name: install dependencies
        run: npm install
   
      #- name: sonarqube scans
       # uses: sonarsource/sonarqube-scan-action@v3
        #env:
         #SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        # SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  
  
      - name: Build an image
        run: |
             docker build -t dosman001/ci-cd:latest .
      - name: login to dockerhub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_TOKEN}}
      - name: push to dockerhub
        run: |
          docker push dosman001/ci-cd:latest

  Deploy:
    runs-on: Linux
    needs: build
    steps: 
      - name: Deploy to minikube
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
  
          
